### ISSUE TITLE
[BUG] Notebooks out of sync with code base?

### ISSUE THREAD

**Issue by aiwalter** [automl/CAAFE#1]
Hi together,

interesting work! I wanted to have a closer look and therefore I tried to run the 2 notebooks but it seems like they are out of sync with current PyPI version of `caafe==0.1.6`. Which version do I need to install to run the notebooks? I tried to fix some installs and imports in the notebooks but still get another exception deeper in the code.

**Comment by noahho** [comment]
Hi Walter,

Thanks for spotting this. I didn't keep these notebooks up-to-date, but there is a colab notebook that I am maintaining: https://colab.research.google.com/drive/1mCA8xOAJZ4MaB_alZvyARTMjhl6RZf0a
This is using the newest Pypi package. If you are running the notebooks provided in this repo, please use the newest caafe version. Since it is hard for me to maintain these different sources, I decided to drop the notebooks in this repo and just point to the colab. Hope that notebook works for you?

I also just noticed I had even left my API keys in the notebooks, even when they were already disabled. Maybe that caused your error, are you using your own OpenAI Access key?

**Comment by aiwalter** [comment]
Ok great thx, I saw the key but thought you have set probably a limit on it for convenience for users.  Dont worry I didnt make more than 5 calls - if even one :)
